# Generated by Django 5.1.6 on 2025-02-11 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_avaliacao_categoria_delete_categoriaavaliacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='habilidade_competencia',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='nivel_engajamento_social',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='valor_emocional',
        ),
    ]
