# Generated by Django 5.1.6 on 2025-02-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_usuario_avaliacao_pontuacao_total_avaliacao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
    ]
